name: Build & Deploy Dev Branch

on:
  push:
    branches-ignore:
      - main
      - gh-pages
      - gh-pages-dev

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true   # fetch themes if used as submodules

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.148.2'  # your tested version
          extended: true

      - name: Build Hugo site
        working-directory: hugo-site
        run: hugo --gc --minify --destination public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages-dev
          publish_dir: ./hugo-site/public
          cname: dev.jenniferpweir.com
