name: Build Hugo Site

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.148.2'
          extended: true

      - name: Build Hugo site
        run: |
          hugo \
            --buildDrafts \
            --disableFastRender \
            --gc \
            --ignoreCache \
            --noHTTPCache \
            --forceSyncStatic \
            --minify