name: Deploy Hugo to dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '1.13.3'

      - name: Build Hugo site
        run: hugo --minify

      - name: Deploy to GitHub Pages (dev)
        uses: peaceiris/actions-gh-pages@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: dev.jenniferpweir.com
