name: Build & Deploy to Production Branch

on:
  push:
    branches:
      # - main
      - "**"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1. Checkout the main branch
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true               # fetch themes if used as submodules

      # 2. Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.148.2'  # your tested version
          extended: true

      # 3. Build the site
      - name: Build Hugo site
        run: hugo --gc --minify --destination public

      # 4. Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./hugo-site/public
          cname: jenniferpweir.com
